/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import database.DMLSQL;
import database.DatabaseManager;
import database.Password;
import database.UserID;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Rohmi Rahmawati
 */
public class login extends javax.swing.JFrame {
    private DatabaseManager dbManager;
    private DMLSQL dmlSql;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.dbManager = new DatabaseManager();
        this.dmlSql = new DMLSQL(this.dbManager);
    }
    
    private void loginSubmit() {
        try {
            String[] columnsToSelect = {"id","email","password"};
            String[] conditionColumns = {"email"};
            String[] operators = {"="};
            Object[] conditionValues = {t_uname.getText()};
            Object[] result = dmlSql.findData("pegawai", columnsToSelect, null, null, conditionColumns, operators, conditionValues, false,false);
            char[] password = t_pw.getPassword();
            String passwordString = new String(password);
            if (result.length == 0) {
                JOptionPane.showMessageDialog(null, "Email Username Tidak Ada !!!");
            } else {
                if (!Password.validatePassword(passwordString,result[2].toString())) {
                    JOptionPane.showMessageDialog(null, "Password Salah !!!");
                } else {
                    UserID.setUserLogin(result[0].toString());
                    JOptionPane.showMessageDialog(null, "Login Berhasil !!!");
                    this.setVisible(false);
                    new layout().setVisible(true);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Login !!!" +e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        t_uname = new javax.swing.JTextField();
        uname = new javax.swing.JLabel();
        pw = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        t_pw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(227, 242, 253));

        judul.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo_tp.png"))); // NOI18N

        t_uname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        uname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        uname.setText("Username");

        pw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pw.setText("Password");

        login.setBackground(new java.awt.Color(0, 0, 204));
        login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        t_pw.setMinimumSize(new java.awt.Dimension(64, 26));
        t_pw.setPreferredSize(new java.awt.Dimension(64, 26));
        t_pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_pwKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pw)
                    .addComponent(uname)
                    .addComponent(t_uname, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_pw, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(uname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pw)
                .addGap(18, 18, 18)
                .addComponent(t_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        loginSubmit();
    }//GEN-LAST:event_loginActionPerformed

    private void t_pwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_pwKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            loginSubmit();
        }
    }//GEN-LAST:event_t_pwKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel judul;
    private javax.swing.JButton login;
    private javax.swing.JLabel pw;
    private javax.swing.JPasswordField t_pw;
    private javax.swing.JTextField t_uname;
    private javax.swing.JLabel uname;
    // End of variables declaration//GEN-END:variables
}
